import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/login');
  await page.getByRole('textbox', { name: 'Email address' }).click();
  await page.getByRole('textbox', { name: 'Email address' }).fill('eniolafaithful577@gmail.com');
  await page.getByRole('textbox', { name: 'Email address' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('Babadadacac@123');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('textbox', { name: 'Password' }).press('Enter');
  await page.getByRole('textbox', { name: 'Search notices...' }).click();
  await page.getByRole('textbox', { name: 'Search notices...' }).fill('');
  await page.getByRole('combobox').selectOption('academic');
  await page.getByRole('combobox').selectOption('facilities');
  await page.getByRole('combobox').selectOption('all');
  await page.getByRole('button', { name: 'New Notice' }).click();
  await page.getByRole('textbox', { name: 'Enter notice title' }).click();
  await page.getByRole('textbox', { name: 'Enter notice title' }).fill('A random notice');
  await page.getByRole('textbox', { name: 'Enter notice content' }).click();
  await page.getByRole('textbox', { name: 'Enter notice content' }).fill('What have I written');
  await page.getByRole('combobox').nth(1).selectOption('academic');
  await page.getByRole('combobox').nth(2).selectOption('medium');
  await page.locator('input[type="datetime-local"]').click();
  await page.locator('input[type="datetime-local"]').click();
  await page.locator('input[type="datetime-local"]').click();
  await page.locator('input[type="datetime-local"]').click();
  await page.locator('input[type="datetime-local"]').click();
  await page.locator('input[type="datetime-local"]').click();
  await page.locator('input[type="datetime-local"]').click();
  await page.locator('input[type="datetime-local"]').click();
  await page.locator('input[type="datetime-local"]').click();
  await page.getByRole('button', { name: 'Create Notice' }).click();
  await page.getByRole('button', { name: 'Live Chat' }).click();
  await page.getByRole('textbox', { name: 'Type your message...' }).click();
  await page.getByRole('textbox', { name: 'Type your message...' }).fill('x');
  await page.getByRole('textbox', { name: 'Type your message...' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Type your message...' }).fill('');
  await page.getByRole('textbox', { name: 'Type your message...' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Type your message...' }).fill('can i send a message here?');
  await page.getByRole('button').nth(4).click();
  await page.getByRole('button', { name: 'Notice Board' }).click();await page.goto('http://localhost:3000/login');
  await page.getByRole('textbox', { name: 'Email address' }).click();
  await page.getByRole('textbox', { name: 'Email address' }).fill('eniolafaithful577@gmail.com');
  await page.getByRole('textbox', { name: 'Email address' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('Babadadacac@123');
  await page.getByRole('textbox', { name: 'Password' }).press('Enter');
  await page.getByRole('textbox', { name: 'Password' }).press('Enter');
  await page.getByRole('textbox', { name: 'Password' }).press('Enter');
  await page.getByRole('textbox', { name: 'Password' }).press('Enter');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Babadadacac@123');
  await page.getByRole('textbox', { name: 'Password' }).press('Enter');
  await page.locator('#wave').nth(1).click();
  await page.locator('#wave').nth(1).click();
  await page.getByRole('button', { name: 'Sign in' }).dblclick();
  await page.goto('http://localhost:3000/board');
  await page.getByRole('button').nth(1).click();
  await page.goto('http://localhost:3000/login');
});